### ISSUE TITLE
windows 11 for arm ?

### ISSUE THREAD

**Issue by gedw99** [naveenrajm7/utm-box#2]
Hey @naveenrajm7 

thank you for the work you have started on the packer / utm integration.

I am playing around with your packer plugin for UTM at the moment.

DO you think its possible to also have windows 11 for arm64.

At the moment I have windows 11 arm64 running with UTM and it runs great, but it is not automated, so when I saw your packer / utm integration I got pretty excited.

I am a golang dev and can help if needed.

**Comment by naveenrajm7** [comment]
Hi @gedw99 

Thank you for looking into the plugin.

I am equally interested in building and providing Windows boxes. 
Yes, I have tried Windows 11 in UTM and it works great.

Appreciate your willingness to help, the plugin currently has all the components required to build a VM from ISO and qcow2 .
We just need to figure out and pin down the steps to do unattended Windows install. 
So if you are aware or come across any way to do unattended windows install, please let me know and we can try to automate that. 

Bento project has few hints - https://github.com/chef/bento/blob/main/packer_templates/win_answer_files/11/arm64/Autounattend.xml
But I do not know what exactly to do, we should start from there.

**Comment by naveenrajm7** [comment]
Hello @gedw99 

Just published Windows 11 ARM UTM box 
https://github.com/naveenrajm7/utm-box/releases/tag/windows-11_v0.0.0

Use it with Vagrant or directly with UTM and let me know how it works.
Thanks for your interest.

**Comment by naveenrajm7** [comment]
Hi @gedw99 

Winget seems interesting.
However, my next goal is to debloat windows and reduce the image size. 

Currently it is at 6GB , which causes problem while image upload and also discourage users to download given the size. 
Once debloating is done, we can discuss about winget and others tools to package with the image.
